[package]
name = "beans"
version = "2.3.0"
authors = ["Adrien Mathieu <adrien.lc.mathieu@gmail.com>"]
license = "MIT OR GPL-3.0-or-later"
edition = "2021"
description = "A parser generator library based on the Earley parser"
homepage = "https://github.com/TheBlackBeans/beans"
repository = "https://github.com/TheBlackBeans/beans"

[dependencies]
newty = "0.5.0"
serde = { version = "1.0.145", features = ["derive", "rc"] }
bincode = "1.3.3"
thiserror = "1.0.37"
fixedbitset = "0.4.2"
clap = { version = "4.0.15", features = ["derive"] }
anyhow = "1.0.65"
fragile = "1.2.1"
itertools = "0.10.5"

[dependencies.unbounded-interval-tree]
version = "1.1.1"
features = ["serde"]
git = "https://github.com/TheBlackBeans/Unbounded-Interval-Tree"
branch = "add-serde"

[dev-dependencies]
criterion = "0.3"
rand = "0.8"
regex = "1"

[[bench]]
name = "regex_benchmark"
harness = false
