[package]
name = "beans"
version = "2.0.0"
authors = ["Adrien Mathieu <adrien.lc.mathieu@gmail.com>"]
license = "MIT OR GPL-3.0-or-later"
edition = "2021"
description = "A parser generator library based on the Earley parser"
homepage = "https://github.com/TheBlackBeans/beans"
repository = "https://github.com/TheBlackBeans/beans"

[dependencies]
newty = "0.4.0"
unbounded-interval-tree = "0.2.3"
serde = { version = "1.0.125", features = ["derive", "rc"] }
bincode = "1.3.2"
thiserror = "1.0.30"
fixedbitset = "0.4.2"
# clap = { version = "~j/2.33.3", features = ["yaml"] }

[dev-dependencies]
criterion = "0.3"
rand = "0.8"
regex = "1"

[[bench]]
name = "regex_benchmark"
harness = false
