[package]
name = "beans"
version = "0.1.0"
authors = ["BlackBeans <adrien.lc.mathieu@gmail.com>"]
edition = "2021"

[dependencies]
hashbrown = { version = "0.11.2", features = ["serde"] }
fixedbitset = { version = "0.4.0", features = ["serde"] }
unbounded-interval-tree = "0.2.3"
serde = { version = "1.0.125", features = ["derive", "rc"] }
bincode = "1.3.2"
thiserror = "1.0.30"
# clap = { version = "~j/2.33.3", features = ["yaml"] }

[dev-dependencies]
criterion = "0.3"
rand = "0.8"
regex = "1"

[[bench]]
name = "regex_benchmark"
harness = false