[package]
name = "macros"
version = "7.0.0"
authors = ["Adrien Mathieu <adrien.lc.mathieu@gmail.com"]
license = "MIT OR GPL-3.0-or-later"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = "1"
quote = "1"
proc-macro2 = "1"
